#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode
from _base_service import BaseService

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.2.6.post2'
__CHEETAH_versionTuple__ = (3, 2, 6, 'post', 2)
__CHEETAH_genTime__ = 1640470275.8940394
__CHEETAH_genTimestamp__ = 'Sat Dec 25 17:11:15 2021'
__CHEETAH_src__ = '_service.tmpl'
__CHEETAH_srcLastModified__ = 'Sat Dec 25 17:10:12 2021'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class service(BaseService):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(service, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        #  see: https://cheetahtemplate.org/users_guide/inheritanceEtc.html#implements
        _v = VFN(VFFSL(SL,"self",True),"init_data",False)() # '$self.init_data()' on line 5, col 1
        if _v is not None: write(_filter(_v, rawExpr='$self.init_data()')) # from line 5, col 1.
        _v = VFN(VFFSL(SL,"self",True),"load_data",False)() # '$self.load_data()' on line 16, col 1
        if _v is not None: write(_filter(_v, rawExpr='$self.load_data()')) # from line 16, col 1.
        #  main Template
        write('''# coding: utf-8
# this is a auto generated file generated by Cheetah
''')
        for frm, imp in VFFSL(SL,"from_imports",True): # generated from line 20, col 1
            write('''from ''')
            _v = VFFSL(SL,"frm",True) # '$frm' on line 21, col 6
            if _v is not None: write(_filter(_v, rawExpr='$frm')) # from line 21, col 6.
            write(''' import ''')
            _v = VFFSL(SL,"imp",True) # '$imp' on line 21, col 18
            if _v is not None: write(_filter(_v, rawExpr='$imp')) # from line 21, col 18.
            write('''
''')
        write('''
class ''')
        _v = VFFSL(SL,"name",True) # '${name}' on line 24, col 7
        if _v is not None: write(_filter(_v, rawExpr='${name}')) # from line 24, col 7.
        write('''(''')
        _v = VFN(VFFSL(SL,"self",True),"lst_to_str",False)(VFFSL(SL,"inherits",True)) # '$self.lst_to_str($inherits)' on line 24, col 15
        if _v is not None: write(_filter(_v, rawExpr='$self.lst_to_str($inherits)')) # from line 24, col 15.
        write(''')''')
        _v = VFN(VFFSL(SL,"self",True),"get_class_end",False)() # '$self.get_class_end()' on line 24, col 43
        if _v is not None: write(_filter(_v, rawExpr='$self.get_class_end()')) # from line 24, col 43.
        write('''
''')
        if VFFSL(SL,"include_desc",True): # generated from line 25, col 1
            write('''    """
''')
            for line in VFN(VFFSL(SL,"self",True),"line_gen",False)(VFFSL(SL,"desc",True)): # generated from line 27, col 5
                write('''    ''')
                _v = VFFSL(SL,"line",True) # '$line' on line 28, col 5
                if _v is not None: write(_filter(_v, rawExpr='$line')) # from line 28, col 5.
                write('''
''')
            if VFFSL(SL,"link",True): # generated from line 30, col 5
                write('''
    See Also:
        `API ''')
                _v = VFFSL(SL,"name",True) # '$name' on line 33, col 14
                if _v is not None: write(_filter(_v, rawExpr='$name')) # from line 33, col 14.
                write(''' <''')
                _v = VFFSL(SL,"link",True) # '$link' on line 33, col 21
                if _v is not None: write(_filter(_v, rawExpr='$link')) # from line 33, col 21.
                write('''>`_
''')
            write('''    """
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    name = ""

    desc = []

    link = ""

    quote = set()

    typings = set()

    inherits = []

    include_desc = True

    from_imports = []

    namespace = ""

    attribs = {}

    _mainCheetahMethod_for_service = 'respond'

## END CLASS DEFINITION

if not hasattr(service, '_initCheetahAttributes'):
    templateAPIClass = getattr(service,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(service)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=service()).run()


