#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode
from _base_struct_dyn import BaseStructDyn

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.2.6.post2'
__CHEETAH_versionTuple__ = (3, 2, 6, 'post', 2)
__CHEETAH_genTime__ = 1644007306.0074997
__CHEETAH_genTimestamp__ = 'Fri Feb  4 15:41:46 2022'
__CHEETAH_src__ = '_struct_dyn.tmpl'
__CHEETAH_srcLastModified__ = 'Fri Feb  4 15:41:38 2022'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class struct_dyn(BaseStructDyn):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(struct_dyn, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        _v = VFN(VFFSL(SL,"self",True),"init_data",False)() # '$self.init_data()' on line 4, col 1
        if _v is not None: write(_filter(_v, rawExpr='$self.init_data()')) # from line 4, col 1.
        #  set is attribs is sorted
        #  str, list, tupple
        #   following attr will get values from BaseStructDyn class
        _v = VFN(VFFSL(SL,"self",True),"load_data",False)() # '$self.load_data()' on line 26, col 1
        if _v is not None: write(_filter(_v, rawExpr='$self.load_data()')) # from line 26, col 1.
        #  Main Template
        safe_name = VFN(VFFSL(SL,"self",True),"get_safe_word",False)(VFFSL(SL,"name",True))
        full_name = VFFSL(SL,"namespace",True) + '.' + VFFSL(SL,"name",True)
        uno_obj_ns = VFFSL(SL,"dyn",True) + VFN(VFN(VFFSL(SL,"full_name",True),"removeprefix",False)('com.sun.star'),"rsplit",False)(sep='.', maxsplit=1)[0]
        uno_obj_in = VFFSL(SL,"uno_obj",True) + VFN(VFFSL(SL,"full_name",True),"removeprefix",False)('com.sun.star')
        write('''# coding: utf-8
''')
        self._handleCheetahInclude("resources/inc_lic.txt", trans=trans, includeFrom="file", raw=True)
        write('''# Struct Class
# this is a auto generated file generated by Cheetah
# Namespace: ''')
        _v = VFFSL(SL,"namespace",True) # '$namespace' on line 36, col 14
        if _v is not None: write(_filter(_v, rawExpr='$namespace')) # from line 36, col 14.
        write('''
''')
        if VFFSL(SL,"libre_office_ver",True): # generated from line 37, col 1
            write('''# Libre Office Version: ''')
            _v = VFFSL(SL,"libre_office_ver",True) # '$libre_office_ver' on line 38, col 25
            if _v is not None: write(_filter(_v, rawExpr='$libre_office_ver')) # from line 38, col 25.
            write('''
''')
        write('''from typing import TYPE_CHECKING
from ooo_uno.oenv import UNO_ENVIRONMENT, UNO_RUNTIME
_DYNAMIC = False
if (not TYPE_CHECKING) and UNO_RUNTIME and UNO_ENVIRONMENT:
    _DYNAMIC = True

if not TYPE_CHECKING and _DYNAMIC:
    def _dynamic_struct() -> None:
        import uno
        # Dynamically create uno struct using uno
        global ''')
        _v = VFFSL(SL,"safe_name",True) # '$safe_name' on line 50, col 16
        if _v is not None: write(_filter(_v, rawExpr='$safe_name')) # from line 50, col 16.
        write('''
        key_order = (''')
        _v = VFN(VFFSL(SL,"self",True),"get_nt_names_str",False)() # '$self.get_nt_names_str()' on line 51, col 22
        if _v is not None: write(_filter(_v, rawExpr='$self.get_nt_names_str()')) # from line 51, col 22.
        write(''')

        def _struct_init(*args, **kwargs):
            arg_len = len(args)
            if arg_len == 1:
                from ''')
        _v = VFFSL(SL,"namespace",True) # '$namespace' on line 56, col 22
        if _v is not None: write(_filter(_v, rawExpr='$namespace')) # from line 56, col 22.
        write(''' import ''')
        _v = VFFSL(SL,"safe_name",True) # '$safe_name' on line 56, col 40
        if _v is not None: write(_filter(_v, rawExpr='$safe_name')) # from line 56, col 40.
        write(''' as U''')
        _v = VFFSL(SL,"safe_name",True) # '${safe_name}' on line 56, col 55
        if _v is not None: write(_filter(_v, rawExpr='${safe_name}')) # from line 56, col 55.
        write('''
                if isinstance(args[0], U''')
        _v = VFFSL(SL,"safe_name",True) # '${safe_name}' on line 57, col 41
        if _v is not None: write(_filter(_v, rawExpr='${safe_name}')) # from line 57, col 41.
        write("""):
                    struct = uno.createUnoStruct(
                        '""")
        _v = VFFSL(SL,"full_name",True) # '${full_name}' on line 59, col 26
        if _v is not None: write(_filter(_v, rawExpr='${full_name}')) # from line 59, col 26.
        write("""', args[0])
                return struct

            struct = uno.createUnoStruct('""")
        _v = VFFSL(SL,"full_name",True) # '${full_name}' on line 62, col 43
        if _v is not None: write(_filter(_v, rawExpr='${full_name}')) # from line 62, col 43.
        write('''\')
            if len(args) > len(key_order):
                raise ValueError("''')
        _v = VFFSL(SL,"safe_name",True) # '${safe_name}' on line 64, col 35
        if _v is not None: write(_filter(_v, rawExpr='${safe_name}')) # from line 64, col 35.
        write('''.__init__() To many parameters")
            for i, arg in enumerate(args):
                setattr(struct, key_order[i], arg)
            for k, v in kwargs.items():
                if k in key_order:
                    setattr(struct, k, v)
            return struct
        ''')
        _v = VFFSL(SL,"safe_name",True) # '$safe_name' on line 71, col 9
        if _v is not None: write(_filter(_v, rawExpr='$safe_name')) # from line 71, col 9.
        write(''' = _struct_init

    _dynamic_struct()
else:
    ''')
        _v = VFN(VFFSL(SL,"self",True),"get_rel_import",False)(in_str=VFFSL(SL,"uno_obj_in",True), ns=VFFSL(SL,"uno_obj_ns",True)) # '$self.get_rel_import(in_str=$uno_obj_in, ns=$uno_obj_ns)' on line 75, col 5
        if _v is not None: write(_filter(_v, rawExpr='$self.get_rel_import(in_str=$uno_obj_in, ns=$uno_obj_ns)')) # from line 75, col 5.
        write(''' as ''')
        _v = VFFSL(SL,"safe_name",True) # '$safe_name' on line 75, col 65
        if _v is not None: write(_filter(_v, rawExpr='$safe_name')) # from line 75, col 65.
        write("""

__all__ = ['""")
        _v = VFFSL(SL,"safe_name",True) # '${safe_name}' on line 77, col 13
        if _v is not None: write(_filter(_v, rawExpr='${safe_name}')) # from line 77, col 13.
        write("""']
""")
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    dynamic_struct = True

    sort = True 

    name = ""

    namespace = ''

    allow_db = True

    libre_office_ver = False

    desc = "" 

    include_desc = True

    link = ""

    requires_typing = False

    inherits = []

    imports = []

    extends_map = {}

    from_imports = []

    from_imports_typing = []

    quote = set()

    typings = set()

    attribs = []

    uno_obj = 'uno_obj'

    dyn = 'dyn'

    _mainCheetahMethod_for_struct_dyn = 'respond'

## END CLASS DEFINITION

if not hasattr(struct_dyn, '_initCheetahAttributes'):
    templateAPIClass = getattr(struct_dyn,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(struct_dyn)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=struct_dyn()).run()


