#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode
import typing
from _base_interface_dyn import BaseInterfaceDyn

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.2.6.post1'
__CHEETAH_versionTuple__ = (3, 2, 6, 'post', 1)
__CHEETAH_genTime__ = 1684195445.679655
__CHEETAH_genTimestamp__ = 'Mon May 15 20:04:05 2023'
__CHEETAH_src__ = '_x_dyn.tmpl'
__CHEETAH_srcLastModified__ = 'Mon May 15 20:03:59 2023'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class x_dyn(BaseInterfaceDyn):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(x_dyn, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        #  see: https://cheetahtemplate.org/users_guide/inheritanceEtc.html#implements
        _v = VFN(VFFSL(SL,"self",True),"init_data",False)() # '$self.init_data()' on line 6, col 1
        if _v is not None: write(_filter(_v, rawExpr='$self.init_data()')) # from line 6, col 1.
        #   following attr will get values from BaseInterfaceDyn class
        _v = VFN(VFFSL(SL,"self",True),"load_data",False)() # '$self.load_data()' on line 28, col 1
        if _v is not None: write(_filter(_v, rawExpr='$self.load_data()')) # from line 28, col 1.
        #  main Template
        safe_name = VFN(VFFSL(SL,"self",True),"get_safe_word",False)(VFFSL(SL,"name",True))
        fullname = VFFSL(SL,"namespace",True) + '.' + VFFSL(SL,"name",True)
        uno_obj_ns = VFFSL(SL,"dyn",True) + VFN(VFN(VFFSL(SL,"fullname",True),"removeprefix",False)('com.sun.star'),"rsplit",False)(sep='.', maxsplit=1)[0]
        uno_obj_in = VFFSL(SL,"uno_obj",True) + VFN(VFFSL(SL,"fullname",True),"removeprefix",False)('com.sun.star')
        uno_helper_namespace = VFFSL(SL,"helper_ns",True) + '.' + VFFSL(SL,"helper_mod",True)
        abc_imports = []
        write('''# coding: utf-8
''')
        self._handleCheetahInclude("resources/inc_lic.txt", trans=trans, includeFrom="file", raw=True)
        write('''# Interface Class
# this is a auto generated file generated by Cheetah
''')
        if VFFSL(SL,"libre_office_ver",True): # generated from line 40, col 1
            write('''# Libre Office Version: ''')
            _v = VFFSL(SL,"libre_office_ver",True) # '$libre_office_ver' on line 41, col 25
            if _v is not None: write(_filter(_v, rawExpr='$libre_office_ver')) # from line 41, col 25.
            write('''
''')
        write('''# Namespace: ''')
        _v = VFFSL(SL,"namespace",True) # '$namespace' on line 43, col 14
        if _v is not None: write(_filter(_v, rawExpr='$namespace')) # from line 43, col 14.
        write('''
import uno
from typing import TYPE_CHECKING
from ''')
        _v = VFFSL(SL,"oenv",True) # '$oenv' on line 46, col 6
        if _v is not None: write(_filter(_v, rawExpr='$oenv')) # from line 46, col 6.
        write(''' import UNO_ENVIRONMENT, UNO_RUNTIME
_DYNAMIC = False
if (not TYPE_CHECKING) and UNO_RUNTIME and UNO_ENVIRONMENT:
    _DYNAMIC = True

if not TYPE_CHECKING and _DYNAMIC:
    from ''')
        _v = VFFSL(SL,"namespace",True) # '$namespace' on line 52, col 10
        if _v is not None: write(_filter(_v, rawExpr='$namespace')) # from line 52, col 10.
        write(''' import ''')
        _v = VFFSL(SL,"safe_name",True) # '$safe_name' on line 52, col 28
        if _v is not None: write(_filter(_v, rawExpr='$safe_name')) # from line 52, col 28.
        write(''' as ''')
        _v = VFFSL(SL,"safe_name",True) # '$safe_name' on line 52, col 42
        if _v is not None: write(_filter(_v, rawExpr='$safe_name')) # from line 52, col 42.
        write('''
    setattr(''')
        _v = VFFSL(SL,"safe_name",True) # '$safe_name' on line 53, col 13
        if _v is not None: write(_filter(_v, rawExpr='$safe_name')) # from line 53, col 13.
        write(""", '__ooo_ns__', '""")
        _v = VFFSL(SL,"namespace",True) # '$namespace' on line 53, col 40
        if _v is not None: write(_filter(_v, rawExpr='$namespace')) # from line 53, col 40.
        write("""')
    setattr(""")
        _v = VFFSL(SL,"safe_name",True) # '$safe_name' on line 54, col 13
        if _v is not None: write(_filter(_v, rawExpr='$safe_name')) # from line 54, col 13.
        write(""", '__ooo_full_ns__', '""")
        _v = VFFSL(SL,"fullname",True) # '$fullname' on line 54, col 45
        if _v is not None: write(_filter(_v, rawExpr='$fullname')) # from line 54, col 45.
        write("""')
    setattr(""")
        _v = VFFSL(SL,"safe_name",True) # '$safe_name' on line 55, col 13
        if _v is not None: write(_filter(_v, rawExpr='$safe_name')) # from line 55, col 13.
        write(""", '__ooo_type_name__', 'interface')
else:
    from """)
        _v = VFFSL(SL,"namespace",True) # '$namespace' on line 57, col 10
        if _v is not None: write(_filter(_v, rawExpr='$namespace')) # from line 57, col 10.
        write(''' import ''')
        _v = VFFSL(SL,"safe_name",True) # '$safe_name' on line 57, col 28
        if _v is not None: write(_filter(_v, rawExpr='$safe_name')) # from line 57, col 28.
        write(''' as ''')
        _v = VFFSL(SL,"safe_name",True) # '$safe_name' on line 57, col 42
        if _v is not None: write(_filter(_v, rawExpr='$safe_name')) # from line 57, col 42.
        write("""

__all__ = ['""")
        _v = VFFSL(SL,"safe_name",True) # '$safe_name' on line 59, col 13
        if _v is not None: write(_filter(_v, rawExpr='$safe_name')) # from line 59, col 13.
        write("""']
""")
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    name = ""

    namespace = ""

    allow_db = True

    libre_office_ver = False

    desc = []

    quote = set()

    typings = set()

    link = ""

    requires_typing = False

    inherits = []

    extends_map = {}

    imports = []

    from_imports = []

    from_imports_typing = []

    attribs = {}

    uno_obj = ''

    dyn = ''

    oenv = ''

    helper_ns = ''

    helper_mod = ''

    _mainCheetahMethod_for_x_dyn = 'respond'

## END CLASS DEFINITION

if not hasattr(x_dyn, '_initCheetahAttributes'):
    templateAPIClass = getattr(x_dyn,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(x_dyn)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=x_dyn()).run()


