# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.ucb
# Libre Office Version: 7.3
"""
Enum



See Also:
    `API IOErrorCode <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1ucb.html#ab0378c2985abaca86838ed9936c3a2d5>`_
"""
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ooo.stubs.uno_enum import UnoEnum

ABORT: 'UnoEnum'
"""
An operation was aborted.
"""
ACCESS_DENIED: 'UnoEnum'
"""
An object cannot be accessed due to insufficient user rights.
"""
ALREADY_EXISTING: 'UnoEnum'
"""
An object already exists.
"""
BAD_CRC: 'UnoEnum'
"""
A bad checksum.
"""
CANT_CREATE: 'UnoEnum'
"""
An object could not be created.
"""
CANT_READ: 'UnoEnum'
"""
Data could not be read from a file.
"""
CANT_SEEK: 'UnoEnum'
"""
A seek operation could not be run.
"""
CANT_TELL: 'UnoEnum'
"""
A tell operation could not be run.
"""
CANT_WRITE: 'UnoEnum'
"""
Data could not be written to a file.
"""
CURRENT_DIRECTORY: 'UnoEnum'
"""
A function is not possible because the path contains the current directory.
"""
DEVICE_NOT_READY: 'UnoEnum'
"""
A device (drive) not ready.
"""
DIFFERENT_DEVICES: 'UnoEnum'
"""
A function is not possible because the devices (drives) are not identical.
"""
GENERAL: 'UnoEnum'
"""
A general input/output error.
"""
INVALID_ACCESS: 'UnoEnum'
"""
An invalid attempt was made to access an object.
"""
INVALID_CHARACTER: 'UnoEnum'
"""
A file name contains invalid characters.
"""
INVALID_DEVICE: 'UnoEnum'
"""
A specified device is invalid.
"""
INVALID_LENGTH: 'UnoEnum'
"""
Invalid data length.
"""
INVALID_PARAMETER: 'UnoEnum'
"""
An operation was started with an invalid parameter.
"""
IS_WILDCARD: 'UnoEnum'
"""
An operation cannot be run on file names containing wildcards.
"""
LOCKING_VIOLATION: 'UnoEnum'
"""
A locking problem.
"""
MISPLACED_CHARACTER: 'UnoEnum'
"""
An invalid file name.
"""
NAME_TOO_LONG: 'UnoEnum'
"""
A file name is too long.
"""
NOT_EXISTING: 'UnoEnum'
"""
A nonexistent object.
"""
NOT_EXISTING_PATH: 'UnoEnum'
"""
The path to a file does not exist.
"""
NOT_SUPPORTED: 'UnoEnum'
"""
An action is not supported.
"""
NO_DIRECTORY: 'UnoEnum'
"""
An object is not a directory.
"""
NO_FILE: 'UnoEnum'
"""
An object is not a file.
"""
OUT_OF_DISK_SPACE: 'UnoEnum'
"""
No more space on a device.
"""
OUT_OF_FILE_HANDLES: 'UnoEnum'
"""
No more file handles available.
"""
OUT_OF_MEMORY: 'UnoEnum'
"""
An operation could not be run due to insufficient memory.
"""
PENDING: 'UnoEnum'
"""
An operation is still pending.
"""
RECURSIVE: 'UnoEnum'
"""
An object cannot be copied into itself.
"""
UNKNOWN: 'UnoEnum'
"""
Unknown.

An unknown I/O error has occurred.
"""
WRITE_PROTECTED: 'UnoEnum'
"""
A function is not possible because the object is write protected.
"""
WRONG_FORMAT: 'UnoEnum'
"""
An incorrect file format.
"""
WRONG_VERSION: 'UnoEnum'
"""
An incorrect file version.
"""

