# coding: utf-8
# this is a auto generated file generated by Cheetah
import os
from collections import namedtuple
from typing import TYPE_CHECKING
from .adjustment_type import AdjustmentType

class AdjustmentEvent(object):
    """
    adjustment event emitted by adjustable objects.

    See Also:
        `API AdjustmentEvent <https://api.libreoffice.org/docs/idl/ref/structcom_1_1sun_1_1star_1_1awt_1_1AdjustmentEvent.html>`_

    Note:
        | At runtime this will be a `namedtuple <https://docs.python.org/3/library/collections.html#collections.namedtuple>`_ and not a class.
        | At design time a class is presumed. This allows for better typings.
        | Effectively functionallity is the same and namedtuple is more efficient than a class.
    """
    def __init__(self, Type: AdjustmentType, Value: int):
        self._Type = Type
        self._Value = Value

    @property
    def Type(self) -> AdjustmentType:
        """
        contains the type of the adjustment event.

        **Libre Office Type:** ``com.sun.star.awt.AdjustmentType``
        """
        return self._Type

    @property
    def Value(self) -> int:
        """
        contains the current value in the adjustment event.

        **Libre Office Type:** ``long``
        """
        return self._Value

def _dynamic_struct():
    # Dynamically create nametuple that is more efficient as stand in for struct

    global AdjustmentEvent
    ignore = os.environ.get('ooouno_ignore_runtime', 'False')
    if ignore == 'True':
        return
    # if statment is to stop VS Code from reporting errors
    if not TYPE_CHECKING:
        AdjustmentEvent = namedtuple('AdjustmentEvent', ['Type', 'Value'])

if not TYPE_CHECKING:
    _dynamic_struct()

__all__ = ['AdjustmentEvent']

