# coding: utf-8
# this is a auto generated file generated by Cheetah
from ...base.const import ConstIntFlagsBase


class FocusChangeReason(ConstIntFlagsBase):
    """
    A combination of these values can be used to specify the reason for a focus change.

    See Also:
        `API FocusChangeReason <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1awt_1_1FocusChangeReason.html>`_
    """
    AROUND = 64
    """
    Changed Focus forward from last to first or backward from first to last.
    """
    BACKWARD = 32
    """
    Changed Focus to the previous control.
    """
    CURSOR = 2
    """
    Focus changed because Key Left/Right/Up/Down was pressed.
    """
    FORWARD = 16
    """
    Changed Focus to the next control.
    """
    MNEMONIC = 4
    """
    Focus changed because mnemonic key was pressed.
    """
    TAB = 1
    """
    Focus changed because TAB was pressed.
    """
    UNIQUEMNEMONIC = 256
    """
    Focus changed because mnemonic key was pressed and this mnemonic is unique.
    """

