# coding: utf-8
# this is a auto generated file generated by Cheetah

class FontWeight(object):
    """
    These values are used to specify whether a font is thin or bold.
    
    They may be expanded in future versions.

    See Also:
        `API FontWeight <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1awt_1_1FontWeight.html>`_
    """
    BLACK = 200.0
    """
    specifies a 200% font weight.
    """
    BOLD = 150.0
    """
    specifies a 150% font weight.
    """
    DONTKNOW = 0.0
    """
    The font weight is not specified/known.
    """
    LIGHT = 75.0
    """
    specifies a 75% font weight.
    """
    NORMAL = 100.0
    """
    specifies a normal font weight.
    """
    SEMIBOLD = 110.0
    """
    specifies a 110% font weight.
    """
    SEMILIGHT = 90.0
    """
    specifies a 90% font weight.
    """
    THIN = 50.0
    """
    specifies a 50% font weight.
    """
    ULTRABOLD = 175.0
    """
    specifies a 175% font weight.
    """
    ULTRALIGHT = 60.0
    """
    specifies a 60% font weight.
    """

