# coding: utf-8
# this is a auto generated file generated by Cheetah
from ...base.const import ConstIntFlagsBase


class FontEmphasisMark(ConstIntFlagsBase):
    """
    These values are used to specify the kind of emphasis mark.
    
    They may be expanded in future versions.

    See Also:
        `API FontEmphasisMark <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1awt_1_1FontEmphasisMark.html>`_
    """
    ABOVE = int('0x1000', 16)
    """
    specifies that the emphasis mark should be positioned above the characters.
    """
    ACCENT = int('0x0004', 16)
    """
    specifies emphasis mark accent.
    """
    BELOW = int('0x2000', 16)
    """
    specifies that the emphasis mark should be positioned below the characters.
    """
    CIRCLE = int('0x0002', 16)
    """
    specifies emphasis mark circle.
    """
    DISC = int('0x0003', 16)
    """
    specifies emphasis mark disc.
    """
    DOT = int('0x0001', 16)
    """
    specifies emphasis mark dot.
    """
    NONE = int('0x0000', 16)
    """
    specifies no emphasis mark.
    """

