# coding: utf-8
# this is a auto generated file generated by Cheetah
from ...base.const import ConstIntBase


class FontRelief(ConstIntBase):
    """
    These values are used to specify the kind of relief.
    
    They may be expanded in future versions.

    See Also:
        `API FontRelief <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1awt_1_1FontRelief.html>`_
    """
    EMBOSSED = 1
    """
    specifies no embossed.
    """
    ENGRAVED = 2
    """
    specifies no engraved.
    """
    NONE = 0
    """
    specifies no relief.
    """

