# coding: utf-8
# this is a auto generated file generated by Cheetah
from ...base.const import ConstIntBase


class ImageScaleMode(ConstIntBase):
    """
    defines modes how an image displayed in a given area should be scaled to fit this area

    See Also:
        `API ImageScaleMode <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1awt_1_1ImageScaleMode.html>`_
    """
    ANISOTROPIC = 2
    """
    specifies that the image should be scaled up or down to the size of the surrounding area anisotropically.
    
    The image will finally cover all of the surrounding area, but its dimensions might be distorted.
    """
    ISOTROPIC = 1
    """
    specifies that the image should be scaled up or down to the size of the surrounding area isotropically, i.e.
    
    by keeping its aspect ratio.
    """
    NONE = 0
    """
    specifies that no scaling should happen at all
    """

