# coding: utf-8
# this is a auto generated file generated by Cheetah
from ...base.const import ConstIntBase


class ImageStatus(ConstIntBase):
    """
    These values are used to specify to which degree an image is available.

    See Also:
        `API ImageStatus <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1awt_1_1ImageStatus.html>`_
    """
    IMAGESTATUS_ABORTED = 4
    """
    This conveys that the image creation process was deliberately aborted.
    """
    IMAGESTATUS_ERROR = 1
    """
    This conveys that an error was encountered while producing the image.
    """
    IMAGESTATUS_SINGLEFRAMEDONE = 2
    """
    This conveys that one frame of the image is complete but there are more frames to be delivered.
    """
    IMAGESTATUS_STATICIMAGEDONE = 3
    """
    This conveys that the image is complete and there are no more pixels or frames to be delivered.
    """

