# coding: utf-8
# this is a auto generated file generated by Cheetah
from ...base.const import ConstIntFlagsBase


class InvalidateStyle(ConstIntFlagsBase):
    """
    specifies how to invalidate windows.

    See Also:
        `API InvalidateStyle <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1awt_1_1InvalidateStyle.html>`_
    """
    CHILDREN = 1
    """
    The child windows are invalidated, too.
    """
    NOCHILDREN = 2
    """
    The child windows are not invalidated.
    """
    NOCLIPCHILDREN = 16384
    """
    The area is invalidated regardless of overlapping child windows.
    """
    NOERASE = 4
    """
    The invalidated area is painted with the background color/pattern.
    """
    NOTRANSPARENT = 32
    """
    The parent window is not invalidated.
    """
    TRANSPARENT = 16
    """
    The parent window is invalidated, too.
    """
    UPDATE = 8
    """
    The invalidated area is updated immediately.
    """

