# coding: utf-8
# this is a auto generated file generated by Cheetah
from ...base.const import ConstIntFlagsBase


class KeyModifier(ConstIntFlagsBase):
    """
    These values are used to specify which modifier keys are pressed.

    See Also:
        `API KeyModifier <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1awt_1_1KeyModifier.html>`_
    """
    MOD1 = 2
    """
    refers in the most cases to the "Ctrl" key (Cmd on macOS).
    """
    MOD2 = 4
    """
    refers in the most cases to the "Alt" key.
    """
    MOD3 = 8
    """
    refers in the most cases to the "Ctrl" key (macOS)
    """
    SHIFT = 1
    """
    refers to both shift keys.
    """

