# coding: utf-8
# this is a auto generated file generated by Cheetah
from ...base.const import ConstIntBase


class MouseWheelBehavior(ConstIntBase):
    """
    describes the scroll behavior of the mouse wheel for a control

    **Since**

        OOo 3.2

    See Also:
        `API MouseWheelBehavior <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1awt_1_1MouseWheelBehavior.html>`_
    """
    SCROLL_ALWAYS = 2
    """
    defines that the mouse can be used to scroll through the control's content, no matter whether or not it has the focus, as long as the mouse pointer is over the control.
    """
    SCROLL_DISABLED = 0
    """
    defines that the mouse wheel cannot be used to scroll through the control's content
    """
    SCROLL_FOCUS_ONLY = 1
    """
    defines that the mouse can only be used to scroll through the control's content if it currently has the focus.
    """

