# coding: utf-8
# this is a auto generated file generated by Cheetah
import os
from collections import namedtuple
from typing import TYPE_CHECKING

class SpinEvent(object):
    """
    specifies a spin button event.

    See Also:
        `API SpinEvent <https://api.libreoffice.org/docs/idl/ref/structcom_1_1sun_1_1star_1_1awt_1_1SpinEvent.html>`_

    Note:
        | At runtime this will be a `namedtuple <https://docs.python.org/3/library/collections.html#collections.namedtuple>`_ and not a class.
        | At design time a class is presumed. This allows for better typings.
        | Effectively functionallity is the same and namedtuple is more efficient than a class.
    """
    def __init__(self, dummy1: int):
        self._dummy1 = dummy1

    @property
    def dummy1(self) -> int:
        """
        This is a dummy field only.
        
        Please ignore.

        **Libre Office Type:** ``short``
        """
        return self._dummy1

def _dynamic_struct():
    # Dynamically create nametuple that is more efficient as stand in for struct

    global SpinEvent
    ignore = os.environ.get('ooouno_ignore_runtime', 'False')
    if ignore == 'True':
        return
    # if statment is to stop VS Code from reporting errors
    if not TYPE_CHECKING:
        SpinEvent = namedtuple('SpinEvent', ['dummy1'])

if not TYPE_CHECKING:
    _dynamic_struct()

__all__ = ['SpinEvent']

