# coding: utf-8
# this is a auto generated file generated by Cheetah
from ...base.const import ConstIntBase


class SystemPointer(ConstIntBase):
    """
    specifies the shape of a mouse pointer.

    See Also:
        `API SystemPointer <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1awt_1_1SystemPointer.html>`_
    """
    ARROW = 0
    """
    specifies the normal arrow-like mouse pointer.
    """
    CHAIN = 70
    """
    specifies a mouse pointer which symbolizes a chain.
    """
    CHAIN_NOTALLOWED = 71
    """
    specifies a mouse pointer which symbolizes "chaining not allowed".
    """
    CHART = 65
    """
    specifies a mouse pointer which symbolizes a chart.
    """
    COPYDATA = 41
    """
    specifies a mouse pointer which symbolizes copying data.
    """
    COPYDATALINK = 44
    """
    specifies a mouse pointer which symbolizes copying a data link.
    """
    COPYFILE = 46
    """
    specifies a mouse pointer which symbolizes copying a file.
    """
    COPYFILELINK = 49
    """
    specifies a mouse pointer which symbolizes copying a file link.
    """
    COPYFILES = 51
    """
    specifies a mouse pointer which symbolizes copying multiple files.
    """
    CROOK = 36
    """
    specifies a crook symbol as mouse pointer.
    """
    CROP = 37
    """
    specifies a crop symbol as mouse pointer.
    """
    CROSS = 5
    """
    specifies a cross as a mouse pointer.
    """
    DETECTIVE = 66
    """
    specifies a mouse pointer which symbolizes a detective.
    """
    DRAW_ARC = 57
    """
    specifies a mouse pointer which symbolizes drawing an arc.
    """
    DRAW_BEZIER = 56
    """
    specifies a mouse pointer which symbolizes drawing a Bezier.
    """
    DRAW_CAPTION = 64
    """
    specifies a mouse pointer which symbolizes drawing a text caption.
    """
    DRAW_CIRCLECUT = 59
    """
    specifies a mouse pointer which symbolizes drawing a circle cut.
    """
    DRAW_CONNECT = 62
    """
    specifies a mouse pointer which symbolizes drawing a connector.
    """
    DRAW_ELLIPSE = 60
    """
    specifies a mouse pointer which symbolizes drawing an ellipse.
    """
    DRAW_FREEHAND = 61
    """
    specifies a mouse pointer which symbolizes drawing free handed.
    """
    DRAW_LINE = 53
    """
    specifies a mouse pointer which symbolizes drawing a line.
    """
    DRAW_PIE = 58
    """
    specifies a mouse pointer which symbolizes drawing a pie.
    """
    DRAW_POLYGON = 55
    """
    specifies a mouse pointer which symbolizes drawing a polygon.
    """
    DRAW_RECT = 54
    """
    specifies a mouse pointer which symbolizes drawing a rectangle.
    """
    DRAW_TEXT = 63
    """
    specifies a mouse pointer which symbolizes drawing text.
    """
    ESIZE = 10
    """
    specifies a mouse pointer which symbolizes resizing for a right border.
    """
    FILL = 31
    """
    specifies a fill symbol as mouse pointer.
    """
    HAND = 27
    """
    specifies a hand symbol as mouse pointer.
    """
    HELP = 4
    """
    specifies a mouse pointer for on-line help.
    """
    HSHEAR = 33
    """
    specifies a horizontal shear symbol as mouse pointer.
    """
    HSIZEBAR = 25
    """
    specifies a mouse pointer which symbolizes horizontal resizing.
    """
    HSPLIT = 23
    """
    specifies a mouse pointer which symbolizes horizontal splitting.
    """
    INVISIBLE = 1
    """
    specifies an invisible mouse pointer.
    """
    LINKDATA = 42
    """
    specifies a mouse pointer which symbolizes linking data.
    """
    LINKFILE = 47
    """
    specifies a mouse pointer which symbolizes linking a file.
    """
    MAGNIFY = 30
    """
    specifies a magnify symbol as mouse pointer.
    """
    MIRROR = 35
    """
    specifies a mirror symbol as mouse pointer.
    """
    MOVE = 6
    """
    specifies a mouse pointer which symbolizes movement.
    """
    MOVEBEZIERWEIGHT = 39
    """
    specifies a mouse pointer which symbolizes moving a Bezier weight.
    """
    MOVEDATA = 40
    """
    specifies a mouse pointer which symbolizes moving data.
    """
    MOVEDATALINK = 43
    """
    specifies a mouse pointer which symbolizes moving a data link.
    """
    MOVEFILE = 45
    """
    specifies a mouse pointer which symbolizes moving a file.
    """
    MOVEFILELINK = 48
    """
    specifies a mouse pointer which symbolizes moving a file link.
    """
    MOVEFILES = 50
    """
    specifies a mouse pointer which symbolizes moving multiple files.
    """
    MOVEPOINT = 38
    """
    specifies a mouse pointer which symbolizes moving a point.
    """
    NESIZE = 12
    """
    specifies a mouse pointer which symbolizes resizing for the top-right corner.
    """
    NOTALLOWED = 52
    """
    specifies a mouse pointer which symbolizes "not allowed".
    """
    NSIZE = 7
    """
    specifies a mouse pointer which symbolizes resizing for a top border.
    """
    NWSIZE = 11
    """
    specifies a mouse pointer which symbolizes resizing for the top-left corner.
    """
    PEN = 29
    """
    specifies a pen symbol as mouse pointer.
    """
    PIVOT_COL = 67
    """
    specifies a mouse pointer which symbolizes a pivot column.
    """
    PIVOT_FIELD = 69
    """
    specifies a mouse pointer which symbolizes a pivot field.
    """
    PIVOT_ROW = 68
    """
    specifies a mouse pointer which symbolizes a pivot row.
    """
    REFHAND = 28
    """
    specifies a pointing hand symbol as mouse pointer.
    """
    ROTATE = 32
    """
    specifies a rotate symbol as mouse pointer.
    """
    SESIZE = 14
    """
    specifies a mouse pointer which symbolizes resizing for the bottom-right corner.
    """
    SSIZE = 8
    """
    specifies a mouse pointer which symbolizes resizing for a bottom border.
    """
    SWSIZE = 13
    """
    specifies a mouse pointer which symbolizes resizing for the bottom-left corner.
    """
    TEXT = 3
    """
    specifies a mouse pointer for text (cursor-like).
    """
    VSHEAR = 34
    """
    specifies a vertical shear symbol as mouse pointer.
    """
    VSIZEBAR = 26
    """
    specifies a mouse pointer which symbolizes vertical resizing.
    """
    VSPLIT = 24
    """
    specifies a mouse pointer which symbolizes vertical splitting.
    """
    WAIT = 2
    """
    specifies a waiting symbol as a mouse pointer (for example hourglass).
    """
    WINDOW_ESIZE = 18
    """
    specifies a mouse pointer which symbolizes window resizing for a right border.
    """
    WINDOW_NESIZE = 20
    """
    specifies a mouse pointer which symbolizes window resizing for the top-right corner.
    """
    WINDOW_NSIZE = 15
    """
    specifies a mouse pointer which symbolizes window resizing for a top border.
    """
    WINDOW_NWSIZE = 19
    """
    specifies a mouse pointer which symbolizes window resizing for the top-left corner.
    """
    WINDOW_SESIZE = 22
    """
    specifies a mouse pointer which symbolizes window resizing for the bottom-right corner.
    """
    WINDOW_SSIZE = 16
    """
    specifies a mouse pointer which symbolizes window resizing for a bottom border.
    """
    WINDOW_SWSIZE = 21
    """
    specifies a mouse pointer which symbolizes window resizing for the bottom-left corner.
    """
    WINDOW_WSIZE = 17
    """
    specifies a mouse pointer which symbolizes window resizing for a left border.
    """
    WSIZE = 9
    """
    specifies a mouse pointer which symbolizes resizing for a left border.
    """

