# coding: utf-8
# this is a auto generated file generated by Cheetah
from ...base.const import ConstIntFlagsBase


class VclWindowPeerAttribute(ConstIntFlagsBase):
    """
    specifies attributes for the VCL window implementation.

    IMPORTANT: These constants have to be disjunct with constants in WindowAttribute.

    See Also:
        `API VclWindowPeerAttribute <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1awt_1_1VclWindowPeerAttribute.html>`_
    """
    AUTOHSCROLL = 1073741824
    AUTOVSCROLL = -2147483648
    CENTER = 2048
    CLIPCHILDREN = 524288
    DEFBUTTON = 65536
    DEF_CANCEL = 268435456
    DEF_NO = -2147483648
    DEF_OK = 134217728
    DEF_RETRY = 536870912
    DEF_YES = 1073741824
    DROPDOWN = 32768
    GROUP = 2097152
    HSCROLL = 256
    LEFT = 1024
    NOBORDER = 1048576
    NOLABEL = 536870912
    OK = 4194304
    OK_CANCEL = 8388608
    READONLY = 262144
    RETRY_CANCEL = 67108864
    RIGHT = 4096
    SORT = 16384
    SPIN = 8192
    VSCROLL = 512
    YES_NO = 16777216
    YES_NO_CANCEL = 33554432

