# coding: utf-8
# this is a auto generated file generated by Cheetah
import os
from collections import namedtuple
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from .uno.x_interface import XInterface

class VclContainerEvent(object):
    """
    specifies a container event.

    These events are provided only for notification purposes.

    See Also:
        `API VclContainerEvent <https://api.libreoffice.org/docs/idl/ref/structcom_1_1sun_1_1star_1_1awt_1_1VclContainerEvent.html>`_

    Note:
        | At runtime this will be a `namedtuple <https://docs.python.org/3/library/collections.html#collections.namedtuple>`_ and not a class.
        | At design time a class is presumed. This allows for better typings.
        | Effectively functionallity is the same and namedtuple is more efficient than a class.
    """
    def __init__(self, Child: 'XInterface'):
        self._Child = Child

    @property
    def Child(self) -> 'XInterface':
        """
        returns the child component that was added or removed.

        **Libre Office Type:** ``com.sun.star.uno.XInterface``
        """
        return self._Child

def _dynamic_struct():
    # Dynamically create nametuple that is more efficient as stand in for struct

    global VclContainerEvent
    ignore = os.environ.get('ooouno_ignore_runtime', 'False')
    if ignore == 'True':
        return
    # if statment is to stop VS Code from reporting errors
    if not TYPE_CHECKING:
        VclContainerEvent = namedtuple('VclContainerEvent', ['Child'])

if not TYPE_CHECKING:
    _dynamic_struct()

__all__ = ['VclContainerEvent']

