# coding: utf-8
# this is a auto generated file generated by Cheetah
from ...base.const import ConstIntBase


class VisualEffect(ConstIntBase):
    """
    These values are used to specify the visual effect of controls.

    The list may grow in future versions.

    See Also:
        `API VisualEffect <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1awt_1_1VisualEffect.html>`_
    """
    FLAT = 2
    """
    specifies a "flat" look
    """
    LOOK3D = 1
    """
    specifies a 3D-like look
    """
    NONE = 0
    """
    specifies that no visual effect is to be applied
    """

