# coding: utf-8
# this is a auto generated file generated by Cheetah
from abc import abstractmethod
from ..lang.x_event_listener import XEventListener
from ..lang.event_object import EventObject


class XActivateListener(XEventListener):
    """
    makes it possible to receive activate events.

    See Also:
        `API XActivateListener <https://api.libreoffice.org/docs/idl/ref/interfacecom_1_1sun_1_1star_1_1awt_1_1XActivateListener.html>`_
    """

    @abstractmethod
    def windowActivated(self, e: EventObject) -> None:
        """
        is invoked when a window is activated.
        
        A window is activated if a child or itself got the focus.
        """
    @abstractmethod
    def windowDeactivated(self, e: EventObject) -> None:
        """
        is invoked when a window is deactivated.
        
        A window is deactivated if a child or itself lost the focus.
        """

