# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.xml.dom
# Libre Office Version: 7.3
"""
Enum

ENUM NodeType

See Also:
    `API NodeType <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1xml_1_1dom.html#acac9cbaeea226ed297804c012dc12b16>`_
"""
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ooo.stubs.uno_enum import UnoEnum

ATTRIBUTE_NODE: 'UnoEnum'
"""
"""
CDATA_SECTION_NODE: 'UnoEnum'
"""
"""
COMMENT_NODE: 'UnoEnum'
"""
"""
DOCUMENT_FRAGMENT_NODE: 'UnoEnum'
"""
"""
DOCUMENT_NODE: 'UnoEnum'
"""
"""
DOCUMENT_TYPE_NODE: 'UnoEnum'
"""
"""
ELEMENT_NODE: 'UnoEnum'
"""
"""
ENTITY_NODE: 'UnoEnum'
"""
"""
ENTITY_REFERENCE_NODE: 'UnoEnum'
"""
"""
NOTATION_NODE: 'UnoEnum'
"""
"""
PROCESSING_INSTRUCTION_NODE: 'UnoEnum'
"""
"""
TEXT_NODE: 'UnoEnum'
"""
"""

