# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.i18n
# Libre Office Version: 7.3
"""
Enum



See Also:
    `API DirectionProperty <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1i18n.html#a6e8fd3df14c13e43a44061c70daacd8b>`_
"""
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ooo.stubs.uno_enum import UnoEnum

ARABIC_NUMBER: 'UnoEnum'
"""
"""
BLOCK_SEPARATOR: 'UnoEnum'
"""
"""
BOUNDARY_NEUTRAL: 'UnoEnum'
"""
"""
COMMON_NUMBER_SEPARATOR: 'UnoEnum'
"""
"""
DIR_NON_SPACING_MARK: 'UnoEnum'
"""
"""
EUROPEAN_NUMBER: 'UnoEnum'
"""
"""
EUROPEAN_NUMBER_SEPARATOR: 'UnoEnum'
"""
"""
EUROPEAN_NUMBER_TERMINATOR: 'UnoEnum'
"""
"""
LEFT_TO_RIGHT: 'UnoEnum'
"""
"""
LEFT_TO_RIGHT_EMBEDDING: 'UnoEnum'
"""
"""
LEFT_TO_RIGHT_OVERRIDE: 'UnoEnum'
"""
"""
OTHER_NEUTRAL: 'UnoEnum'
"""
"""
POP_DIRECTIONAL_FORMAT: 'UnoEnum'
"""
"""
RIGHT_TO_LEFT: 'UnoEnum'
"""
"""
RIGHT_TO_LEFT_ARABIC: 'UnoEnum'
"""
"""
RIGHT_TO_LEFT_EMBEDDING: 'UnoEnum'
"""
"""
RIGHT_TO_LEFT_OVERRIDE: 'UnoEnum'
"""
"""
SEGMENT_SEPARATOR: 'UnoEnum'
"""
"""
WHITE_SPACE_NEUTRAL: 'UnoEnum'
"""
"""

