# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.i18n
# Libre Office Version: 7.3
"""
Enum



See Also:
    `API UnicodeScript <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1i18n.html#a47be7d1d06e067d647f387cc160d5e29>`_
"""
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ooo.stubs.uno_enum import UnoEnum

kAlphabeticPresentation: 'UnoEnum'
"""
"""
kArabic: 'UnoEnum'
"""
"""
kArabicPresentationA: 'UnoEnum'
"""
"""
kArabicPresentationB: 'UnoEnum'
"""
"""
kArmenian: 'UnoEnum'
"""
"""
kArrow: 'UnoEnum'
"""
"""
kBasicLatin: 'UnoEnum'
"""
"""
kBengali: 'UnoEnum'
"""
"""
kBlockElement: 'UnoEnum'
"""
"""
kBopomofo: 'UnoEnum'
"""
"""
kBopomofoExtended: 'UnoEnum'
"""
"""
kBoxDrawing: 'UnoEnum'
"""
"""
kBraillePatterns: 'UnoEnum'
"""
"""
kCJKCompatibility: 'UnoEnum'
"""
"""
kCJKCompatibilityForm: 'UnoEnum'
"""
"""
kCJKCompatibilityIdeograph: 'UnoEnum'
"""
"""
kCJKRadicalsSupplement: 'UnoEnum'
"""
"""
kCJKSymbolPunctuation: 'UnoEnum'
"""
"""
kCJKUnifiedIdeograph: 'UnoEnum'
"""
"""
kCJKUnifiedIdeographsExtensionA: 'UnoEnum'
"""
"""
kCherokee: 'UnoEnum'
"""
"""
kCombiningDiacritical: 'UnoEnum'
"""
"""
kCombiningHalfMark: 'UnoEnum'
"""
"""
kControlPicture: 'UnoEnum'
"""
"""
kCurrencySymbolScript: 'UnoEnum'
"""
"""
kCyrillic: 'UnoEnum'
"""
"""
kDevanagari: 'UnoEnum'
"""
"""
kDingbat: 'UnoEnum'
"""
"""
kEnclosedAlphanumeric: 'UnoEnum'
"""
"""
kEnclosedCJKLetterMonth: 'UnoEnum'
"""
"""
kEthiopic: 'UnoEnum'
"""
"""
kGeneralPunctuation: 'UnoEnum'
"""
"""
kGeometricShape: 'UnoEnum'
"""
"""
kGeorgian: 'UnoEnum'
"""
"""
kGreek: 'UnoEnum'
"""
"""
kGreekExtended: 'UnoEnum'
"""
"""
kGujarati: 'UnoEnum'
"""
"""
kGurmukhi: 'UnoEnum'
"""
"""
kHalfwidthFullwidthForm: 'UnoEnum'
"""
"""
kHangulCompatibilityJamo: 'UnoEnum'
"""
"""
kHangulJamo: 'UnoEnum'
"""
"""
kHangulSyllable: 'UnoEnum'
"""
"""
kHebrew: 'UnoEnum'
"""
"""
kHighPrivateUseSurrogate: 'UnoEnum'
"""
"""
kHighSurrogate: 'UnoEnum'
"""
"""
kHiragana: 'UnoEnum'
"""
"""
kIPAExtension: 'UnoEnum'
"""
"""
kIdeographicDescriptionCharacters: 'UnoEnum'
"""
"""
kKanbun: 'UnoEnum'
"""
"""
kKangxiRadicals: 'UnoEnum'
"""
"""
kKannada: 'UnoEnum'
"""
"""
kKatakana: 'UnoEnum'
"""
"""
kKhmer: 'UnoEnum'
"""
"""
kLao: 'UnoEnum'
"""
"""
kLatin1Supplement: 'UnoEnum'
"""
"""
kLatinExtendedA: 'UnoEnum'
"""
"""
kLatinExtendedAdditional: 'UnoEnum'
"""
"""
kLatinExtendedB: 'UnoEnum'
"""
"""
kLetterlikeSymbol: 'UnoEnum'
"""
"""
kLowSurrogate: 'UnoEnum'
"""
"""
kMalayalam: 'UnoEnum'
"""
"""
kMathOperator: 'UnoEnum'
"""
"""
kMiscSymbol: 'UnoEnum'
"""
"""
kMiscTechnical: 'UnoEnum'
"""
"""
kMongolian: 'UnoEnum'
"""
"""
kMyanmar: 'UnoEnum'
"""
"""
kNoScript: 'UnoEnum'
"""
"""
kNumberForm: 'UnoEnum'
"""
"""
kOgham: 'UnoEnum'
"""
"""
kOpticalCharacter: 'UnoEnum'
"""
"""
kOriya: 'UnoEnum'
"""
"""
kPrivateUse: 'UnoEnum'
"""
"""
kRunic: 'UnoEnum'
"""
"""
kScriptCount: 'UnoEnum'
"""
"""
kSinhala: 'UnoEnum'
"""
"""
kSmallFormVariant: 'UnoEnum'
"""
"""
kSpacingModifier: 'UnoEnum'
"""
"""
kSuperSubScript: 'UnoEnum'
"""
"""
kSymbolCombiningMark: 'UnoEnum'
"""
"""
kSyriac: 'UnoEnum'
"""
"""
kTamil: 'UnoEnum'
"""
"""
kTelugu: 'UnoEnum'
"""
"""
kThaana: 'UnoEnum'
"""
"""
kThai: 'UnoEnum'
"""
"""
kTibetan: 'UnoEnum'
"""
"""
kUnifiedCanadianAboriginalSyllabics: 'UnoEnum'
"""
"""
kYiRadicals: 'UnoEnum'
"""
"""
kYiSyllables: 'UnoEnum'
"""
"""

