#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode
from _struct_base import struct_base as s_base

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.2.6.post2'
__CHEETAH_versionTuple__ = (3, 2, 6, 'post', 2)
__CHEETAH_genTime__ = 1638332137.6899261
__CHEETAH_genTimestamp__ = 'Tue Nov 30 23:15:37 2021'
__CHEETAH_src__ = '/home/paul/Documents/Projects/Python/Cheeta3/ooo_uno_tmpl/uno_obj/awt/DeviceInfo.tmpl'
__CHEETAH_srcLastModified__ = 'Tue Nov 30 23:15:29 2021'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class DeviceInfo(s_base):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(DeviceInfo, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    sort = True

    name = "DeviceInfo"

    desc = """contains information about a device."""

    link = "https://api.libreoffice.org/docs/idl/ref/structcom_1_1sun_1_1star_1_1awt_1_1DeviceInfo.html"

    imports = []

    from_imports = []

    attribs = [    {        "name": "BitsPerPixel",        "type": "int",        "orig_type": "short",        "lines": "contains the color-depth of the device."    },    {        "name": "BottomInset",        "type": "int",        "orig_type": "long",        "lines": "contains the inset from the bottom."    },    {        "name": "Capabilities",        "type": "int",        "orig_type": "long",        "lines": "specifies special operations which are possible on the device."    },    {        "name": "Height",        "type": "int",        "orig_type": "long",        "lines": "contains the height of the device in pixels."    },    {        "name": "LeftInset",        "type": "int",        "orig_type": "long",        "lines": "contains the inset from the left."    },    {        "name": "PixelPerMeterX",        "type": "float",        "orig_type": "double",        "lines": "contains the X-axis resolution of the device in pixel/meter."    },    {        "name": "PixelPerMeterY",        "type": "float",        "orig_type": "double",        "lines": "contains the Y-axis resolution of the device in pixel/meter."    },    {        "name": "RightInset",        "type": "int",        "orig_type": "long",        "lines": "contains the inset from the right."    },    {        "name": "TopInset",        "type": "int",        "orig_type": "long",        "lines": "contains the inset from the top."    },    {        "name": "Width",        "type": "int",        "orig_type": "long",        "lines": "contains the width of the device in pixels."    }]

    _mainCheetahMethod_for_DeviceInfo = 'writeBody'

## END CLASS DEFINITION

if not hasattr(DeviceInfo, '_initCheetahAttributes'):
    templateAPIClass = getattr(DeviceInfo,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(DeviceInfo)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=DeviceInfo()).run()


