#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode
from _struct_base import struct_base as s_base

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.2.6.post2'
__CHEETAH_versionTuple__ = (3, 2, 6, 'post', 2)
__CHEETAH_genTime__ = 1638340585.657374
__CHEETAH_genTimestamp__ = 'Wed Dec  1 01:36:25 2021'
__CHEETAH_src__ = '/home/paul/Documents/Projects/Python/Cheeta3/ooo_uno_tmpl/uno_obj/awt/Gradient.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Dec  1 01:33:15 2021'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class Gradient(s_base):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(Gradient, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    sort = True

    name = "Gradient"

    desc = """Describes a gradient between two colors.

    Many aspects of the gradient are undefined, like the algorithm and color space to use to interpolate between the colors and what "intensity" means."""

    link = "https://api.libreoffice.org/docs/idl/ref/structcom_1_1sun_1_1star_1_1awt_1_1Gradient.html"

    imports = []

    from_imports = []

    auto_imports = [('.util.color', 'Color'), ('.gradient_style', 'GradientStyle')]

    attribs = [    {        "name": "Angle",        "type": "int",        "orig_type": "short",        "lines": "angle of the gradient in 1/10 degree."    },    {        "name": "Border",        "type": "int",        "orig_type": "short",        "lines": "per cent of the total width where just the start color is used."    },    {        "name": "EndColor",        "type": "'Color'",        "orig_type": "com.sun.star.util.Color",        "lines": "specifies the color at the end point of the gradient."    },    {        "name": "EndIntensity",        "type": "int",        "orig_type": "short",        "lines": "specifies the intensity at the end point of the gradient."    },    {        "name": "StartColor",        "type": "'Color'",        "orig_type": "com.sun.star.util.Color",        "lines": "specifies the color at the start point of the gradient."    },    {        "name": "StartIntensity",        "type": "int",        "orig_type": "short",        "lines": ["Specifies the intensity at the start point of the gradient.",            "",            "What that means is undefined."]    },    {        "name": "StepCount",        "type": "int",        "orig_type": "short",        "lines": ["Specifies the number of steps of change color.",            "",            "What that means is undefined."]    },    {        "name": "Style",        "type": "'GradientStyle'",        "orig_type": "com.sun.star.awt.GradientStyle",        "lines": "specifies the style of the gradient."    },    {        "name": "XOffset",        "type": "int",        "orig_type": "short",        "lines": ["Specifies the X-coordinate, where the gradient begins.",            "",            "This is effectively the center of the RADIAL, ELLIPTICAL, SQUARE and RECT style gradients."]    },    {        "name": "YOffset",        "type": "int",        "orig_type": "short",        "lines": ["Specifies the Y-coordinate, where the gradient begins.",            "",            "See previous field."]    }]

    _mainCheetahMethod_for_Gradient = 'writeBody'

## END CLASS DEFINITION

if not hasattr(Gradient, '_initCheetahAttributes'):
    templateAPIClass = getattr(Gradient,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(Gradient)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=Gradient()).run()


