#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode
from _const_base import const_base as c_base

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.2.6.post2'
__CHEETAH_versionTuple__ = (3, 2, 6, 'post', 2)
__CHEETAH_genTime__ = 1638299549.7635367
__CHEETAH_genTimestamp__ = 'Tue Nov 30 14:12:29 2021'
__CHEETAH_src__ = '/home/paul/Documents/Projects/Python/Cheeta3/ooo_uno/uno_obj/awt/MessageBoxButtons.tmpl'
__CHEETAH_srcLastModified__ = 'Tue Nov 30 14:12:25 2021'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class MessageBoxButtons(c_base):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(MessageBoxButtons, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        #  set is const_dict is sorted
        #  $from_imports is a tuple eg: $from_imports = [('.tab_align', 'TabAlign')]
        #  $const_dict, Comment can be string or list or tupple eg:
        # 
        # $const_dict = {
        #     "NONE": ("0", "No column or page break is applied."),
        # }
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    hex = True

    sort = True 

    flags = False

    name = "MessageBoxButtons"

    desc = "defines constants for the possible message box button combinations."

    imports = []

    from_imports = []

    link = "https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1awt_1_1MessageBoxButtons.html"

    const_dict = {    "BUTTONS_OK": ("0x1", [        'specifies a message with "OK" button.'    ]),    "BUTTONS_OK_CANCEL": ("0x2", [        'specifies a message box with "OK" and "CANCEL" button.'    ]),    "BUTTONS_YES_NO": ("0x3", [        'specifies a message box with "YES" and "NO" button.'    ]),    "BUTTONS_YES_NO_CANCEL": ("0x4", [        'specifies a message box with "YES", "NO" and "CANCEL" button.'    ]),    "BUTTONS_RETRY_CANCEL": ("0x5", [        'specifies a message box with "RETRY" and "CANCEL" button.'    ]),    "BUTTONS_ABORT_IGNORE_RETRY": ("0x6", [        'specifies a message box with "ABORT", "IGNORE" and "RETRY" button.'    ]),    "DEFAULT_BUTTON_OK": ("0x10000", [        "specifies that OK is the default button."    ]),    "DEFAULT_BUTTON_CANCEL": ("0x20000", [        "specifies that CANCEL is the default button."    ]),    "DEFAULT_BUTTON_RETRY": ("0x30000", [        "specifies that RETRY is the default button."    ]),    "DEFAULT_BUTTON_YES": ("0x40000", [        "specifies that YES is the default button."    ]),    "DEFAULT_BUTTON_NO": ("0x50000", [        "specifies that NO is the default button."    ]),    "DEFAULT_BUTTON_IGNORE": ("0x60000", [        "specifies that IGNORE is the default button."    ])}

    _mainCheetahMethod_for_MessageBoxButtons = 'writeBody'

## END CLASS DEFINITION

if not hasattr(MessageBoxButtons, '_initCheetahAttributes'):
    templateAPIClass = getattr(MessageBoxButtons,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(MessageBoxButtons)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=MessageBoxButtons()).run()


