# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.xml.xpath
# Libre Office Version: 7.3
"""
Enum

ENUM XPathObjectType

See Also:
    `API XPathObjectType <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1xml_1_1xpath.html#a4e7de3ae7d09203486b85490e0a6f1a3>`_
"""
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ooo.stubs.uno_enum import UnoEnum

XPATH_BOOLEAN: 'UnoEnum'
"""
"""
XPATH_LOCATIONSET: 'UnoEnum'
"""
"""
XPATH_NODESET: 'UnoEnum'
"""
"""
XPATH_NUMBER: 'UnoEnum'
"""
"""
XPATH_POINT: 'UnoEnum'
"""
"""
XPATH_RANGE: 'UnoEnum'
"""
"""
XPATH_STRING: 'UnoEnum'
"""
"""
XPATH_UNDEFINED: 'UnoEnum'
"""
"""
XPATH_USERS: 'UnoEnum'
"""
"""
XPATH_XSLT_TREE: 'UnoEnum'
"""
"""

