# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.uno
# Libre Office Version: 7.3
"""
Enum



See Also:
    `API TypeClass <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1uno.html#a00683ed3ec24b47c36ead10a20d6f328>`_
"""
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ooo.stubs.uno_enum import UnoEnum

ANY: 'UnoEnum'
"""
reflecting the any type; anys can carry any UNO value except of any values
"""
ARRAY: 'UnoEnum'
"""
Deprecated, UNOIDL does not have an array concept.
"""
BOOLEAN: 'UnoEnum'
"""
reflecting the boolean type; true and false
"""
BYTE: 'UnoEnum'
"""
reflecting the 8-bit ordinal type
"""
CHAR: 'UnoEnum'
"""
reflecting the 16-bit unicode character type
"""
CONSTANT: 'UnoEnum'
"""
reflecting constants
"""
CONSTANTS: 'UnoEnum'
"""
reflecting constants groups
"""
DOUBLE: 'UnoEnum'
"""
reflecting the 64-bit floating point type
"""
ENUM: 'UnoEnum'
"""
reflecting enum types
"""
EXCEPTION: 'UnoEnum'
"""
reflecting exception types
"""
FLOAT: 'UnoEnum'
"""
reflecting the 32-bit floating point type
"""
HYPER: 'UnoEnum'
"""
reflecting the signed 64-bit ordinal type
"""
INTERFACE: 'UnoEnum'
"""
reflecting interface types
"""
INTERFACE_ATTRIBUTE: 'UnoEnum'
"""
reflecting interface attributes
"""
INTERFACE_METHOD: 'UnoEnum'
"""
reflecting interface methods
"""
LONG: 'UnoEnum'
"""
reflecting the signed 32-bit ordinal type
"""
MODULE: 'UnoEnum'
"""
reflecting modules
"""
PROPERTY: 'UnoEnum'
"""
reflecting properties
"""
SEQUENCE: 'UnoEnum'
"""
reflecting sequence types
"""
SERVICE: 'UnoEnum'
"""
reflecting services
"""
SHORT: 'UnoEnum'
"""
reflecting the signed 16-bit ordinal type
"""
SINGLETON: 'UnoEnum'
"""
reflecting singletons
"""
STRING: 'UnoEnum'
"""
reflecting the string type; strings of unicode characters
"""
STRUCT: 'UnoEnum'
"""
reflecting compound types
"""
TYPE: 'UnoEnum'
"""
reflecting the meta type
"""
TYPEDEF: 'UnoEnum'
"""
reflecting typedefed types referencing other types
"""
UNION: 'UnoEnum'
"""
Deprecated, UNOIDL does not have a union concept.
"""
UNKNOWN: 'UnoEnum'
"""
reflecting the unreflectable type
"""
UNSIGNED_HYPER: 'UnoEnum'
"""
reflecting the unsigned 64-bit ordinal type
"""
UNSIGNED_LONG: 'UnoEnum'
"""
reflecting the unsigned 32-bit type
"""
UNSIGNED_SHORT: 'UnoEnum'
"""
reflecting the unsigned 16-bit ordinal type
"""
VOID: 'UnoEnum'
"""
reflecting the void type; denotes no type
"""

